export type ToolEntry={id:string;name:string;source:string;layer:string;status:"registered"|"adapter-ready"|"integration-ready";kind:"repo"|"service"|"resource"};
export const toolingCatalog:ToolEntry[]=[
{id:"ruvview",name:"RuvView",source:"RuvView",layer:"Visualization",status:"registered",kind:"repo"},
{id:"asc",name:"ASC",source:"ASC",layer:"Research",status:"registered",kind:"repo"},
{id:"voice-studio",name:"Voice Studio",source:"Voice Studio",layer:"Voice",status:"registered",kind:"repo"},
{id:"myro-fish",name:"MiroFish",source:"MiroFish",layer:"Simulation",status:"registered",kind:"repo"},
{id:"open-research",name:"Open Research",source:"Open Research",layer:"Research",status:"registered",kind:"repo"},
{id:"atlas",name:"Atlas",source:"Atlas",layer:"Research",status:"registered",kind:"repo"},
{id:"pi-compact-toolkit",name:"P-I Compact Tool Kit",source:"P-I Compact Tool Kit",layer:"OSINT",status:"registered",kind:"repo"},
{id:"agent-lightning",name:"Agent Lightning",source:"Agent Lightning",layer:"Agents",status:"registered",kind:"repo"},
{id:"open-deep-research",name:"Open Deep Research",source:"Open Deep Research",layer:"Research",status:"registered",kind:"repo"},
{id:"clean-robots",name:"Clean Robots",source:"Clean Robots",layer:"Automation",status:"registered",kind:"repo"},
{id:"micro-fish",name:"Micro Fish",source:"Micro Fish",layer:"Simulation",status:"registered",kind:"repo"},
{id:"little-davy-mimic",name:"Little Davy Mimic",source:"Little Davy Mimic",layer:"Extraction",status:"registered",kind:"repo"},
{id:"paperclip-ai",name:"Paperclip AI",source:"Paperclip AI",layer:"Agents",status:"registered",kind:"repo"},
{id:"gods-eye-view",name:"God's Eye View",source:"God's Eye View",layer:"Visualization",status:"registered",kind:"repo"},
{id:"thu-maic",name:"THU MAIC",source:"THU MAIC",layer:"Agents",status:"registered",kind:"repo"},
{id:"magnitude-dev",name:"Magnitude Dev",source:"Magnitude Dev",layer:"Development",status:"registered",kind:"repo"},
{id:"evri-open-seo",name:"Evri Open SEO",source:"Evri Open SEO",layer:"SEO",status:"registered",kind:"repo"},
{id:"snailsploit-cloud-red",name:"Snailsploit / Cloud Red",source:"Snailsploit / Cloud Red",layer:"Security",status:"registered",kind:"repo"},
{id:"fincept-manual",name:"Fincept Manual",source:"Fincept Manual",layer:"MarketResearch",status:"registered",kind:"repo"},
{id:"heygen",name:"HeyGen",source:"HeyGen",layer:"Media",status:"registered",kind:"service"},
{id:"hyperframes",name:"Hyperframes",source:"Hyperframes",layer:"Media",status:"registered",kind:"repo"},
{id:"ghost-track",name:"Ghost Track",source:"Ghost Track",layer:"OSINT",status:"registered",kind:"repo"},
{id:"it-dlp",name:"IT-DLP",source:"IT-DLP",layer:"Security",status:"registered",kind:"repo"},
{id:"ollama",name:"Ollama",source:"Ollama",layer:"ModelRuntime",status:"registered",kind:"service"},
{id:"ilias-vl",name:"Ilias VL",source:"Ilias VL",layer:"Vision",status:"registered",kind:"repo"},
{id:"whisper",name:"OpenAI Whisper",source:"OpenAI Whisper",layer:"Voice",status:"registered",kind:"repo"},
{id:"plausible",name:"Plausible Community Edition",source:"Plausible CE",layer:"Analytics",status:"registered",kind:"repo"},
{id:"penpot-mcp",name:"Penpot MCP",source:"Penpot MCP",layer:"Design",status:"registered",kind:"repo"},
{id:"n8n",name:"n8n",source:"n8n IO",layer:"Automation",status:"registered",kind:"service"},
{id:"calcom",name:"Cal.com",source:"Cal.com",layer:"Scheduling",status:"registered",kind:"service"},
{id:"open-notebook",name:"Open Notebook",source:"IF Novo / Open Notebook",layer:"Knowledge",status:"registered",kind:"repo"},
{id:"browser-use",name:"Browser Use",source:"browser-use/browser-use",layer:"ComputerAgent",status:"adapter-ready",kind:"repo"},
{id:"agentmemory",name:"AgentMemory",source:"rohitg00/agentmemory",layer:"AgentMemory",status:"adapter-ready",kind:"repo"},
{id:"scientific-agent-skills",name:"Scientific Agent Skills",source:"K-Dense-AI/scientific-agent-skills",layer:"ResearchAgent",status:"adapter-ready",kind:"repo"},
{id:"diagram-design",name:"Diagram Design",source:"cathrynlavery/diagram-design",layer:"Visualization",status:"adapter-ready",kind:"repo"},
{id:"anthropic-cybersecurity-skills",name:"Anthropic Cybersecurity Skills",source:"mukul975/Anthropic-Cybersecurity-Skills",layer:"SecurityResearch",status:"adapter-ready",kind:"repo"},
{id:"awesome-harness-engineering",name:"Awesome Harness Engineering",source:"harness-engineer/awesome-harness-engineering",layer:"HarnessEngineering",status:"adapter-ready",kind:"repo"},
{id:"openviking",name:"OpenViking",source:"volcengine/OpenViking",layer:"ContextDatabase",status:"adapter-ready",kind:"repo"},
{id:"langflow",name:"Langflow",source:"Langflow",layer:"Agents",status:"registered",kind:"repo"},
{id:"supabase",name:"Supabase",source:"Supabase",layer:"Data",status:"registered",kind:"service"},
{id:"stirling-pdf",name:"Stirling PDF",source:"Stirling PDF",layer:"Documents",status:"registered",kind:"repo"},
{id:"crawl-for-ai",name:"Crawl for AI",source:"Crawl for AI",layer:"WebResearch",status:"registered",kind:"repo"},
{id:"difi",name:"DIFI",source:"DIFI",layer:"Research",status:"registered",kind:"repo"},
{id:"reverse-image-search",name:"Reverse Image Search",source:"Reverse Image Search",layer:"OSINT",status:"registered",kind:"service"},
{id:"wayback-machine",name:"Wayback Machine",source:"Wayback Machine",layer:"WebArchive",status:"registered",kind:"service"},
{id:"taylor-wessing-toolkit",name:"Taylor Wessing Data Breach Toolkit",source:"phishdestroy/taylor-wessing-data-breach-toolkit",layer:"EvidenceIntegrity",status:"adapter-ready",kind:"repo"},
{id:"worldcam",name:"WorldCam",source:"worldcam.io",layer:"OSINT",status:"registered",kind:"service"},
{id:"blackvault",name:"The Black Vault",source:"theblackvault.com",layer:"OSINT",status:"registered",kind:"service"},
{id:"maigret",name:"Maigret",source:"soxoj/maigret",layer:"OSINT",status:"registered",kind:"repo"},
{id:"trape",name:"Trape",source:"jofpin/trape",layer:"OSINT",status:"registered",kind:"repo"},
{id:"blackbird-osint",name:"Blackbird",source:"p1ngul1n0/blackbird",layer:"OSINT",status:"adapter-ready",kind:"repo"},
{id:"computer-use",name:"Computer Use",source:"trycua/cua",layer:"ComputerAgent",status:"adapter-ready",kind:"repo"},
{id:"edge-llm",name:"LiteRT-LM",source:"google-ai-edge/LiteRT-LM",layer:"EdgeRuntime",status:"adapter-ready",kind:"repo"},
{id:"fincept-terminal",name:"Fincept Terminal",source:"Fincept-Corporation/FinceptTerminal",layer:"MarketResearch",status:"adapter-ready",kind:"repo"},
{id:"chronos",name:"Chronos Forecasting",source:"amazon-science/chronos-forecasting",layer:"ForecastingEngine",status:"adapter-ready",kind:"repo"},
{id:"ml-intern",name:"Hugging Face ML Intern",source:"huggingface/ml-intern",layer:"ResearchAgent",status:"adapter-ready",kind:"repo"},
{id:"deeptutor",name:"DeepTutor",source:"HKUDS/DeepTutor",layer:"KnowledgeAgent",status:"registered",kind:"repo"},
{id:"pixelle-video",name:"Pixelle Video",source:"AIDC-AI/Pixelle-Video",layer:"MediaPipeline",status:"registered",kind:"repo"},
{id:"openscreen",name:"OpenScreen",source:"siddharthvaddem/openscreen",layer:"EvidenceCapture",status:"registered",kind:"repo"},
{id:"ds2api",name:"DeepSeek API Bridge",source:"CJackHwang/ds2api",layer:"ProviderAdapter",status:"registered",kind:"repo"},
{id:"systematic-trading",name:"Awesome Systematic Trading",source:"paperswithbacktest/awesome-systematic-trading",layer:"MarketResearch",status:"adapter-ready",kind:"repo"},
{id:"model-gateway",name:"Model Gateway",source:"Alishahryar1/free-claude-code",layer:"ModelRouter",status:"adapter-ready",kind:"repo"},
{id:"autoharness",name:"AutoHarness",source:"tigerless-labs/autoharness",layer:"SelfLearning",status:"adapter-ready",kind:"repo"},
{id:"opencode-runtime",name:"OpenCode Server Runtime",source:"OpenCode",layer:"AgentRuntime",status:"adapter-ready",kind:"repo"},
{id:"mimo-v2-6-pro",name:"MiMo-V2.6-Pro",source:"Xiaomi MiMo",layer:"FrontierModel",status:"registered",kind:"resource"},
{id:"cognee",name:"Cognee",source:"topoteretes/cognee",layer:"Knowledge",status:"adapter-ready",kind:"repo"},
{id:"graft",name:"Graft",source:"NanoNets/Graft",layer:"CodeIntelligence",status:"adapter-ready",kind:"repo"},
{id:"openmontage",name:"OpenMontage",source:"calesthio/OpenMontage",layer:"MediaPipeline",status:"adapter-ready",kind:"repo"},
{id:"codebase-memory-mcp",name:"Codebase Memory MCP",source:"DeusData/codebase-memory-mcp",layer:"CodeIntelligence",status:"adapter-ready",kind:"repo"},
{id:"argos-atlas",name:"ARGOS ATLAS",source:"argosatlas.com",layer:"GeoOSINT",status:"adapter-ready",kind:"service"},
{id:"grounded-api",name:"Grounded API / GroundedSLAM",source:"Grounded Superintelligence",layer:"SpatialIntelligence",status:"adapter-ready",kind:"service"},
];